### PR TITLE
Fixed MoreCompany not working in unity editor

### PR DESCRIPTION
**Pull request by 1A3Dev**
- Fixed MoreCompany erroring when trying to load within unity editor.

### CODE REVIEW

**Comment by notnotnotswipez** [comment]
Silly PR

**Comment by 1A3Dev** [comment]
> Silly PR

True however there's not really any reason against it as it doesn't change anything if not using unity editor.

**Comment by notnotnotswipez** [comment]
Not planning on merging PRs like this as it just propagates more silly PRs. (Equivalent to “empty line removal” PRs)

**Comment by 1A3Dev** [comment]
I tried it a few weeks back and had a BepInEx error when `Application.persistentDataPath` & `Paths.PluginPath` were defined outside of the awake. Had this fix in my uncommitted files so thought I might as well fix it for anyone else that wants to try it in unity editor.

**Pull request closed without merging**
